Traceback (most recent call last):
  File "C:\Users\Gladiator\trading-lab\common\error_handling.py", line 313, in wrap_with_error_capture
    result = with_backoff(
             ^^^^^^^^^^^^^
  File "C:\Users\Gladiator\trading-lab\common\error_handling.py", line 102, in with_backoff
    return fn()
           ^^^^
  File "C:\Users\Gladiator\trading-lab\orchestrator\orchestrate.py", line 53, in <lambda>
    return wrapper(lambda: executor(context), context=context, mlflow_cfg=mlflow_cfg, max_retries=max_retries)
                           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\trading-lab\orchestrator\execute.py", line 30, in run_one_core
    equity, trades = strat.run(df, run_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\trading-lab\strategies\SOPRRegimeBand.py", line 163, in run
    sopr_d = _prepare_sopr(price_d.index, df, run_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\trading-lab\strategies\SOPRRegimeBand.py", line 115, in _prepare_sopr
    s = _load_sopr_from_csv(sopr_csv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\trading-lab\strategies\SOPRRegimeBand.py", line 73, in _load_sopr_from_csv
    df = pd.read_csv(path)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\anaconda3\envs\tradebot\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\anaconda3\envs\tradebot\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\anaconda3\envs\tradebot\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gladiator\anaconda3\envs\tradebot\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\Gladiator\anaconda3\envs\tradebot\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data\\metrics\\sopr@1d.csv'
